<?php

/**
 * @file
 * Photswipe integration with Drupal module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * The minimum PhotoSwipe version we support.
 */
define('PHOTOSWIPE_MIN_PLUGIN_VERSION', '4.0.0');


/**
 * Implements hook_theme().
 */
function photoswipe_theme() {
  return array(
    'photoswipe_image_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'display_settings' => array(),
      ),
      'file' => 'photoswipe.theme.inc',
    ),
    'photoswipe_container' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function photoswipe_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the photoswipe module
    case 'help.page.photoswipe':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('<a href=":url">Photoswipe</a> provides a nice javascript-based display for photo galleries, very sleek on mobile browsers.', array(
        ':url' => 'http://www.photoswipe.com/')) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_libraries_info().
 */
function photoswipe_libraries_info() {
  $libraries['photoswipe'] = array(
    'name' => 'Photoswipe plugin',
    'vendor url' => 'http://photoswipe.com',
    'download url' => 'https://github.com/dimsemenov/PhotoSwipe/archive/v4.1.0.zip',
    'path' => 'dist',
    'version arguments' => array(
      'file' => 'dist/photoswipe.min.js',
      'pattern' => '@(?i:PhotoSwipe)\s-\sv?([0-9\.a-z]+)@',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'photoswipe.min.js',
        'photoswipe-ui-default.min.js'
      ),
      'css' => array(
        'photoswipe.css',
        'default-skin/default-skin.css'
      )
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'photoswipe.min.js',
            'photoswipe-ui-default.min.js'
          ),
          'css' => array(
            'photoswipe.css'
          )
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'photoswipe.js',
            'photoswipe-ui-default.js'
          ),
          'css' => array(
            'photoswipe.css',
            'default-skin/default-skin.css'
          )
        ),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_page_attachments().
 */
function photoswipe_page_attachments(array &$attachments) {
  // Conditionally load on an admin page
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();

  if (\Drupal::config('photoswipe.settings')->get('photoswipe_always_load_non_admin') && $is_admin) {
    photoswipe_load_assets($attachments);
  }
}

/**
 * Implements hook_page_bottom().
 */
function photoswipe_page_bottom(array &$page_bottom) {
  // Load the Container HTML at the bottom of the page
  if (photoswipe_assets_loaded()) {
    $page_bottom['photoswipe'] = array(
      '#theme' => 'photoswipe_container',
    );
  }
}

/**
 * Loads photoswipe assets.
 */
function photoswipe_load_assets(array &$attachments) {
  if (!photoswipe_assets_loaded()) {
    // Add the library of Photoswipe assets
    $attachments['#attached']['library'][] = 'photoswipe/photoswipe';
    // Load initialization file
    $attachments['#attached']['library'][] = 'photoswipe/photoswipe.init';

    // Add photoswipe js settings.
    $settings = \Drupal::config('photoswipe.settings')->get('options');
    $attachments['#attached']['drupalSettings']['photoswipe']['options'] = $settings;

    photoswipe_assets_loaded(TRUE);
  }
}

/**
 * Stores whether photoswipe assets has been loaded in the same request.
 *
 * @param bool $loaded
 *   (Optional) Set whether assets are loaded or not.
 *
 * @return bool
 */
function photoswipe_assets_loaded($loaded = NULL) {
  $status = &drupal_static(__FUNCTION__);

  if ($loaded) {
    $status = $loaded;
  }

  return $status;
}
